services:
  db:
    image: postgres:17
    restart: unless-stopped
    environment:
      POSTGRES_DB: teenwallet
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: "Veer@2025"
    volumes:
      - db_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d teenwallet"]
      interval: 5s
      retries: 5
    ports: ["5432:5432"]        

  api:
    build: .
    depends_on:
      db:
        condition: service_healthy
    restart: unless-stopped
    volumes:
      - ./configs/docker.yaml:/app/configs/local.yaml:ro
    ports:
      - "8080:8080"

volumes:
  db_data:
