env: "development"

http_server:
  address: "0.0.0.0:8080"

postgres:
  host: "db"
  port: 5432
  user: "postgres"
  password: "Veer@2025"
  dbname: "teenwallet"
  sslmode: "disable"

jwt:
  secret: "super-secret-key"
